baseURL = "http://e-zyme.com/"
languageCode = "en-us"
title = "E-ZYME"
theme = 'mediumish'
summaryLength = 100
copyright = 'Clare Vladimirskij - All rights reserved'
disqusShortname = 'shortDisquis'

[params]
logo = "/images/logo_ezyme.png"
description = "a catalyst for learning"
customCSS = []

[params.author]
name = "Clare Vladimirskij"
thumbnail = "/images/author.png"
description = "Creator of this blog."

[params.index]
picture = "/images/logo_ezyme.png"
title = "E-ZYME"
subtitle = "A catalyst for learning."
mdtext = '''E-ZYME is an educational site for students and researchers in Life Sciences with a special focus on medicinal chemistry and cheminformatics. Additionally E-ZYME endeavours to bring cutting edge research from female scientists to the forefront and promote women in STEM / MINT sectors. The author of the E-ZYME Blog is [Dr. Clare Vladimirskij](/static/author), a Medicinal Chemist originally from the UK, who now resides in Germany.
'''
alertbar = true

[params.social]
github = "<username>"
linkedin = "dr-clare-vladimirskij-24315b72"
xing = "<username>"
medium = "<username>"
twitter = "<username>"
instagram = "<username>"


## Main Menu
[[menu.main]]
name = "E-ZYME"
identifier = "about"
weight = 100
url = "/"
[[menu.main]]
name = "Blog"
weight = 200
identifier = "blog"
url = "/blog"
[[menu.main]]
name = "Author"
identifier = "author"
weight = 300
url = "/static/author"

